import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import {
  EntityDirectoryEntrySchema,
  OperationsDaySchema,
  OperationsQuerySchema,
  OperationsResponseSchema,
  seesOperations,
  type DataQuality,
  type MeasureValue,
  type OperationsAttendance,
  type OperationsDay,
  type OperationsNow,
} from '@orbit/contracts';
import { membershipOf } from '../../plugins/auth.ts';
import { ApiError } from '../../plugins/errors.ts';
import type { ModuleDeps } from '../ports.ts';
import { auditRead, parseInput, parseRows } from '../shared.ts';

const Count = z.number().int().min(0);
const Timestamp = z.iso.datetime({ offset: true });

/** One row of `orbit_erp.ops_snapshot()`, as db/operations.ts aliases it. */
const SnapshotRowSchema = z.strictObject({
  facilityId: z.uuid(),
  today: z.iso.date(),
  asOf: Timestamp,
  activeStaff: Count,
  rosteredToday: Count,
  onDutyNow: Count,
  lateToday: Count,
  missingPunchToday: Count,
  absentToday: Count,
  doctorsTotal: Count,
  doctorsActive: Count,
  doctorsExpiring: Count,
  doctorsExpired: Count,
  doctorsSuspended: Count,
  openVisits: Count,
  openInpatients: Count,
  visitsStartedToday: Count,
  visitsStarted7d: Count,
  servicesToday: Count,
  services7d: Count,
  pendingCorrections: Count,
  lastActivityAt: Timestamp.nullable(),
});
type SnapshotRow = z.infer<typeof SnapshotRowSchema>;

const DailyRowSchema = OperationsDaySchema.extend({ facilityId: z.uuid() });

const FRESH_MS = 2 * 60 * 60 * 1000;
const LATE_MS = 24 * 60 * 60 * 1000;

const LIMITATIONS = [
  'Hospital operations are simulated: people, visits and punches are generated by the demonstration, not taken from a real hospital.',
  'These counts come from the hospital operations system. They are not comparable to the KPI scorecard, which models full-size hospitals; the two are never merged.',
];

function emptyNow(): OperationsNow {
  return {
    staffing: { activeStaff: 0, rosteredToday: 0, onDutyNow: 0, lateToday: 0, missingPunchToday: 0, absentToday: 0 },
    doctors: { total: 0, credentialActive: 0, credentialExpiring: 0, credentialExpired: 0, credentialSuspended: 0 },
    visits: { openNow: 0, openInpatients: 0, startedToday: 0, startedLast7Days: 0 },
    services: { deliveredToday: 0, deliveredLast7Days: 0 },
    pendingCorrections: 0,
  };
}

function nowOf(row: SnapshotRow): OperationsNow {
  return {
    staffing: {
      activeStaff: row.activeStaff,
      rosteredToday: row.rosteredToday,
      onDutyNow: row.onDutyNow,
      lateToday: row.lateToday,
      missingPunchToday: row.missingPunchToday,
      absentToday: row.absentToday,
    },
    doctors: {
      total: row.doctorsTotal,
      credentialActive: row.doctorsActive,
      credentialExpiring: row.doctorsExpiring,
      credentialExpired: row.doctorsExpired,
      credentialSuspended: row.doctorsSuspended,
    },
    visits: {
      openNow: row.openVisits,
      openInpatients: row.openInpatients,
      startedToday: row.visitsStartedToday,
      startedLast7Days: row.visitsStarted7d,
    },
    services: { deliveredToday: row.servicesToday, deliveredLast7Days: row.services7d },
    pendingCorrections: row.pendingCorrections,
  };
}

function addNow(a: OperationsNow, b: OperationsNow): OperationsNow {
  return {
    staffing: {
      activeStaff: a.staffing.activeStaff + b.staffing.activeStaff,
      rosteredToday: a.staffing.rosteredToday + b.staffing.rosteredToday,
      onDutyNow: a.staffing.onDutyNow + b.staffing.onDutyNow,
      lateToday: a.staffing.lateToday + b.staffing.lateToday,
      missingPunchToday: a.staffing.missingPunchToday + b.staffing.missingPunchToday,
      absentToday: a.staffing.absentToday + b.staffing.absentToday,
    },
    doctors: {
      total: a.doctors.total + b.doctors.total,
      credentialActive: a.doctors.credentialActive + b.doctors.credentialActive,
      credentialExpiring: a.doctors.credentialExpiring + b.doctors.credentialExpiring,
      credentialExpired: a.doctors.credentialExpired + b.doctors.credentialExpired,
      credentialSuspended: a.doctors.credentialSuspended + b.doctors.credentialSuspended,
    },
    visits: {
      openNow: a.visits.openNow + b.visits.openNow,
      openInpatients: a.visits.openInpatients + b.visits.openInpatients,
      startedToday: a.visits.startedToday + b.visits.startedToday,
      startedLast7Days: a.visits.startedLast7Days + b.visits.startedLast7Days,
    },
    services: {
      deliveredToday: a.services.deliveredToday + b.services.deliveredToday,
      deliveredLast7Days: a.services.deliveredLast7Days + b.services.deliveredLast7Days,
    },
    pendingCorrections: a.pendingCorrections + b.pendingCorrections,
  };
}

/** A percentage of finished shifts; with none finished it is not applicable, never zero (PRD §7.9). */
function rate(count: number, finished: number): MeasureValue {
  if (finished === 0) return { status: 'not_applicable', reason: 'zero_denominator' };
  return { status: 'available', value: Math.round((count / finished) * 1000) / 10 };
}

/** Finished shifts are those no longer in progress; every rate divides by them. */
function attendanceOf(days: readonly OperationsDay[], periodDays: number): OperationsAttendance {
  const sum = (pick: (day: OperationsDay) => number): number => days.reduce((total, day) => total + pick(day), 0);
  const onTime = sum((d) => d.onTime);
  const late = sum((d) => d.late);
  const earlyExit = sum((d) => d.earlyExit);
  const missingPunch = sum((d) => d.missingPunch);
  const absent = sum((d) => d.absent);
  const finished = sum((d) => d.rostered) - sum((d) => d.inProgress);
  const completed = onTime + late + earlyExit;
  return {
    days: periodDays,
    finished,
    completed,
    onTime,
    late,
    earlyExit,
    missingPunch,
    absent,
    completionRate: rate(completed, finished),
    onTimeRate: rate(onTime, finished),
    missingPunchRate: rate(missingPunch, finished),
    absentRate: rate(absent, finished),
  };
}

function sumDays(days: readonly OperationsDay[]): OperationsDay[] {
  const byDate = new Map<string, OperationsDay>();
  for (const day of days) {
    const have = byDate.get(day.date);
    byDate.set(
      day.date,
      have
        ? {
            date: day.date,
            rostered: have.rostered + day.rostered,
            inProgress: have.inProgress + day.inProgress,
            onTime: have.onTime + day.onTime,
            late: have.late + day.late,
            earlyExit: have.earlyExit + day.earlyExit,
            missingPunch: have.missingPunch + day.missingPunch,
            absent: have.absent + day.absent,
            onLeave: have.onLeave + day.onLeave,
          }
        : day,
    );
  }
  return [...byDate.values()].sort((a, b) => a.date.localeCompare(b.date));
}

function qualityOf(asOf: string, lastActivity: readonly (string | null)[]): DataQuality {
  const latest = lastActivity.filter((at): at is string => at !== null).sort().at(-1) ?? null;
  const age = latest === null ? Infinity : Date.parse(asOf) - Date.parse(latest);
  return {
    state: 'illustrative',
    reconciliation: 'not_applicable',
    freshness: age <= FRESH_MS ? 'current' : age <= LATE_MS ? 'late' : 'stale',
    refreshedAt: latest ?? asOf,
    limitations: latest === null ? [...LIMITATIONS, 'The hospital operations system has recorded nothing yet.'] : LIMITATIONS,
  };
}

/**
 * Leadership's live view of the hospital operations data (ADR 0018):
 * `GET /api/operations`. Aggregates only, for the hospitals the caller's
 * verified scope covers. Two gates: the role allow-list here, and the database
 * functions, which apply the scope themselves. A role outside the list is
 * refused, never shown an empty page that looks complete.
 */
export function registerOperationsRoutes(api: FastifyInstance, deps: ModuleDeps): void {
  api.get('/operations', async (request) => {
    const membership = membershipOf(request);
    if (!seesOperations(membership.role)) {
      throw new ApiError('forbidden', 'Your role does not include hospital operations.', 'operations_role_not_permitted');
    }
    const { days } = parseInput(OperationsQuerySchema, request.query);

    const [snapshotRows, dailyRows, entityRows] = await Promise.all([
      deps.operations.snapshot(membership),
      deps.operations.daily(membership, days),
      deps.entities.visible(membership),
    ]);
    const snapshots = parseRows(SnapshotRowSchema, snapshotRows, 'operations_snapshot_failed_contract');
    const daily = parseRows(DailyRowSchema, dailyRows, 'operations_daily_failed_contract');
    const names = new Map(
      parseRows(EntityDirectoryEntrySchema, entityRows, 'entity_row_failed_contract')
        .filter((entry) => entry.grain === 'facility')
        .map((entry) => [entry.entityId, entry.label] as const),
    );

    // Defense in depth: a hospital the caller cannot see by name is a source defect, not a row to drop.
    for (const { facilityId } of [...snapshots, ...daily]) {
      if (!names.has(facilityId)) {
        throw new ApiError('internal', 'An internal error occurred.', 'operations_returned_out_of_scope_hospital');
      }
    }

    const hospitals = snapshots
      .map((row) => ({
        facilityId: row.facilityId,
        name: names.get(row.facilityId) as string,
        now: nowOf(row),
        attendance: attendanceOf(
          daily.filter((day) => day.facilityId === row.facilityId),
          days,
        ),
        daily: daily
          .filter((day) => day.facilityId === row.facilityId)
          .map(({ facilityId: _facility, ...day }) => day),
        lastActivityAt: row.lastActivityAt,
      }))
      .sort((a, b) => a.name.localeCompare(b.name));

    const first = snapshots[0];
    const asOf = first ? first.asOf : new Date().toISOString();
    const rollupDaily = sumDays(hospitals.flatMap((hospital) => hospital.daily));
    const response = OperationsResponseSchema.parse({
      source: 'hospital-operations',
      asOf,
      today: first ? first.today : asOf.slice(0, 10),
      periodDays: days,
      scope: membership.scopes,
      rollup: {
        hospitals: hospitals.length,
        now: hospitals.reduce((total, hospital) => addNow(total, hospital.now), emptyNow()),
        attendance: attendanceOf(rollupDaily, days),
        daily: rollupDaily,
      },
      hospitals,
      dataQuality: qualityOf(asOf, snapshots.map((row) => row.lastActivityAt)),
      provenance: 'illustrative',
      disclosure: deps.disclosure,
    });

    await auditRead(deps, request, membership, {
      kind: 'evidence_viewed',
      target: { type: 'route', id: 'operations' },
      outcome: 'served',
    });
    return response;
  });
}
