-- =========================================================================
-- 0003_seeded_exceptions.sql
--
-- GENERATED FILE — DO NOT EDIT BY HAND.
-- Produced by packages/data-gen/scripts/generate-observations.ts
-- Dataset checksum: 7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e
-- Exceptions      : 7 labelled seeded scenarios (below approved budget, latest month)
--
-- Illustrative synthetic data (PRD §8.4). Idempotent. Requires seed 0002.
-- Needs Maruti's plausibility review before an external demo (PRD §8.2).
-- =========================================================================

begin;

create temp table _entities (grain text, slug text, id uuid) on commit drop;
insert into _entities select 'group', o.slug, o.id from orbit.organizations o where o.slug = 'kestrion';
insert into _entities select 'region', r.slug, r.id from orbit.regions r join orbit.organizations o on o.id = r.organization_id where o.slug = 'kestrion';
insert into _entities select 'facility', f.slug, f.id from orbit.facilities f join orbit.organizations o on o.id = f.organization_id where o.slug = 'kestrion';

-- Labelled seeded scenarios (PRD FR-03): derived from the rows above, not a reviewed rule.
insert into orbit.exceptions (exception_key, organization_id, dataset_id, assignment_id, entity_grain, entity_id, period_cadence, period_start, period_end, priority, category, comparison_basis, detection, what_changed, why_it_matters, owner_role, evidence, data_quality)
select v.exception_key, d.organization_id, d.id, v.assignment_id, v.grain, e.id, 'month', v.period_start::date, v.period_end::date, v.priority, 'performance', 'budget', v.detection::jsonb, v.what_changed, v.why_it_matters, v.owner_role, v.evidence::jsonb, v.data_quality::jsonb
from (values
  ('exc:regional-coo:regional-net-revenue-vs-approved-budget:region:north:2026-08', 'regional-coo:regional-net-revenue-vs-approved-budget', 'region', 'north', '2026-08-01', '2026-08-31', 'act_now', '{"kind":"seeded_scenario","scenarioLabel":"Demo scenario: below approved budget in the latest month (seeded from the illustrative dataset, not a reviewed rule)"}', 'Regional net revenue vs approved budget was 99.1% of approved budget in August 2026, against 102.6% in July 2026.', 'This KPI carries 15% of the Regional COO scorecard weight in the KPI framework.', 'regional-coo', '{"observationIds":["obs:regional-coo:regional-net-revenue-vs-approved-budget:region:north:2026-08","obs:regional-coo:regional-net-revenue-vs-approved-budget:region:north:2026-07"],"definitionVersion":"v1","datasetChecksum":"7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e"}', '{"state":"illustrative","reconciliation":"reconciled","freshness":"current","refreshedAt":"2026-09-02T06:00:00.000Z","limitations":[]}'),
  ('exc:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:avenhurst:2026-08', 'hospital-dho:hospital-net-revenue-vs-approved-budget', 'facility', 'avenhurst', '2026-08-01', '2026-08-31', 'monitor', '{"kind":"seeded_scenario","scenarioLabel":"Demo scenario: below approved budget in the latest month (seeded from the illustrative dataset, not a reviewed rule)"}', 'Hospital net revenue vs approved budget was 98.6% of approved budget in August 2026, against 104.2% in July 2026.', 'This KPI carries 15% of the Hospital DHO scorecard weight in the KPI framework.', 'hospital-dho', '{"observationIds":["obs:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:avenhurst:2026-08","obs:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:avenhurst:2026-07"],"definitionVersion":"v1","datasetChecksum":"7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e"}', '{"state":"illustrative","reconciliation":"reconciled","freshness":"current","refreshedAt":"2026-09-02T06:00:00.000Z","limitations":[]}'),
  ('exc:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:brackmoor:2026-08', 'hospital-dho:hospital-net-revenue-vs-approved-budget', 'facility', 'brackmoor', '2026-08-01', '2026-08-31', 'monitor', '{"kind":"seeded_scenario","scenarioLabel":"Demo scenario: below approved budget in the latest month (seeded from the illustrative dataset, not a reviewed rule)"}', 'Hospital net revenue vs approved budget was 99.2% of approved budget in August 2026, against 98.8% in July 2026.', 'This KPI carries 15% of the Hospital DHO scorecard weight in the KPI framework.', 'hospital-dho', '{"observationIds":["obs:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:brackmoor:2026-08","obs:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:brackmoor:2026-07"],"definitionVersion":"v1","datasetChecksum":"7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e"}', '{"state":"illustrative","reconciliation":"reconciled","freshness":"current","refreshedAt":"2026-09-02T06:00:00.000Z","limitations":[]}'),
  ('exc:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:calderwyn:2026-08', 'hospital-dho:hospital-net-revenue-vs-approved-budget', 'facility', 'calderwyn', '2026-08-01', '2026-08-31', 'monitor', '{"kind":"seeded_scenario","scenarioLabel":"Demo scenario: below approved budget in the latest month (seeded from the illustrative dataset, not a reviewed rule)"}', 'Hospital net revenue vs approved budget was 99.9% of approved budget in August 2026, against 104.3% in July 2026.', 'This KPI carries 15% of the Hospital DHO scorecard weight in the KPI framework.', 'hospital-dho', '{"observationIds":["obs:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:calderwyn:2026-08","obs:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:calderwyn:2026-07"],"definitionVersion":"v1","datasetChecksum":"7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e"}', '{"state":"illustrative","reconciliation":"reconciled","freshness":"current","refreshedAt":"2026-09-02T06:00:00.000Z","limitations":[]}'),
  ('exc:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:elverton:2026-08', 'hospital-dho:hospital-net-revenue-vs-approved-budget', 'facility', 'elverton', '2026-08-01', '2026-08-31', 'act_now', '{"kind":"seeded_scenario","scenarioLabel":"Demo scenario: below approved budget in the latest month (seeded from the illustrative dataset, not a reviewed rule)"}', 'Hospital net revenue vs approved budget was 96.6% of approved budget in August 2026, against 100.1% in July 2026.', 'This KPI carries 15% of the Hospital DHO scorecard weight in the KPI framework.', 'hospital-dho', '{"observationIds":["obs:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:elverton:2026-08","obs:hospital-dho:hospital-net-revenue-vs-approved-budget:facility:elverton:2026-07"],"definitionVersion":"v1","datasetChecksum":"7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e"}', '{"state":"illustrative","reconciliation":"reconciled","freshness":"current","refreshedAt":"2026-09-02T06:00:00.000Z","limitations":[]}'),
  ('exc:hospital-dho:hospital-ebitda-vs-approved-budget:facility:brackmoor:2026-08', 'hospital-dho:hospital-ebitda-vs-approved-budget', 'facility', 'brackmoor', '2026-08-01', '2026-08-31', 'monitor', '{"kind":"seeded_scenario","scenarioLabel":"Demo scenario: below approved budget in the latest month (seeded from the illustrative dataset, not a reviewed rule)"}', 'Hospital EBITDA vs approved budget was 94.3% of approved budget in August 2026, against 90.6% in July 2026.', 'This KPI carries 12% of the Hospital DHO scorecard weight in the KPI framework.', 'hospital-dho', '{"observationIds":["obs:hospital-dho:hospital-ebitda-vs-approved-budget:facility:brackmoor:2026-08","obs:hospital-dho:hospital-ebitda-vs-approved-budget:facility:brackmoor:2026-07"],"definitionVersion":"v1","datasetChecksum":"7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e"}', '{"state":"illustrative","reconciliation":"reconciled","freshness":"current","refreshedAt":"2026-09-02T06:00:00.000Z","limitations":[]}'),
  ('exc:hospital-dho:hospital-ebitda-vs-approved-budget:facility:elverton:2026-08', 'hospital-dho:hospital-ebitda-vs-approved-budget', 'facility', 'elverton', '2026-08-01', '2026-08-31', 'act_now', '{"kind":"seeded_scenario","scenarioLabel":"Demo scenario: below approved budget in the latest month (seeded from the illustrative dataset, not a reviewed rule)"}', 'Hospital EBITDA vs approved budget was 77.7% of approved budget in August 2026, against 107.2% in July 2026.', 'This KPI carries 12% of the Hospital DHO scorecard weight in the KPI framework.', 'hospital-dho', '{"observationIds":["obs:hospital-dho:hospital-ebitda-vs-approved-budget:facility:elverton:2026-08","obs:hospital-dho:hospital-ebitda-vs-approved-budget:facility:elverton:2026-07"],"definitionVersion":"v1","datasetChecksum":"7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e"}', '{"state":"illustrative","reconciliation":"reconciled","freshness":"current","refreshedAt":"2026-09-02T06:00:00.000Z","limitations":[]}')
) as v(exception_key, assignment_id, grain, slug, period_start, period_end, priority, detection, what_changed, why_it_matters, owner_role, evidence, data_quality)
join _entities e on e.grain = v.grain and e.slug = v.slug
join orbit.datasets d on d.checksum = '7fbceb8f37faf11136017b2f1a4aa108d37f3fbcd21ee5251b0b0ae1712e503e'
join orbit.organizations o on o.id = d.organization_id and o.slug = 'kestrion'
on conflict (dataset_id, exception_key) do nothing;

commit;
