-- GENERATED by packages/data-gen/scripts/generate-erp-seed.ts. Do not edit by hand.
-- Reference data: settings, departments, specialties, shift patterns, services.
-- Fictional demonstration records (ADR 0016). Illustrative; not clinical or employment data.
-- Idempotent. Requires migration 20261001000100_orbit_erp_operations.sql and seed 0001.

begin;

insert into orbit_erp.erp_settings (organization_id, late_grace_minutes, early_exit_grace_minutes,
  punch_window_before_minutes, punch_window_after_minutes, credential_warning_days)
select (select id from orbit.organizations where slug = 'kestrion'), 10, 10, 120, 240, 30
on conflict (organization_id) do nothing;
insert into orbit_erp.departments (id, organization_id, code, name)
select v.id::uuid, (select id from orbit.organizations where slug = 'kestrion'), v.code, v.name from (values
  ('af491ddc-9f1d-4e2e-b4ed-935d43eec9de', 'OPD', 'Outpatients'),
  ('9884675b-012d-4c61-a6b7-028f860f2f3a', 'WARD', 'Inpatient wards'),
  ('f370ed28-008c-4b70-9684-59899e61eeaf', 'EMER', 'Emergency'),
  ('555cdc1c-7580-4b3c-a235-22ff88ed3810', 'ICU', 'Critical care'),
  ('45624a5d-3112-40a6-9ed4-70de032872c4', 'LAB', 'Laboratory'),
  ('c95cfb7c-4416-4680-862d-d341e9b731ed', 'RAD', 'Radiology'),
  ('d4b0953b-c9e2-4931-9772-2d303ab5e628', 'CARD', 'Cardiac sciences'),
  ('579b6047-b83e-456a-928f-78feb79b61fd', 'ORTH', 'Orthopaedics'),
  ('29fa1aff-6ad8-476b-bb97-7db9ae6e407d', 'ONCO', 'Oncology'),
  ('c612fddd-0166-443f-9440-e924efb720c5', 'REHAB', 'Rehabilitation'),
  ('3d760709-df18-440d-b5bb-d4aaaca5864f', 'ADMIN', 'Administration'),
  ('6e6bdac4-b151-47ed-b62f-51bf8229a14b', 'SUPP', 'Support services')
) as v(id, code, name)
on conflict (id) do nothing;
insert into orbit_erp.specialties (id, organization_id, code, name)
select v.id::uuid, (select id from orbit.organizations where slug = 'kestrion'), v.code, v.name from (values
  ('c838499a-e5a4-40d9-88c4-30001c9709f8', 'GEN', 'General medicine'),
  ('27ce28ec-9adb-4917-a1f6-8da2fcfaa044', 'EMER', 'Emergency medicine'),
  ('c6fd8fcc-1f23-45b0-bdb6-5f7d5f52637f', 'CRIT', 'Critical care'),
  ('f80af988-814d-4f48-b653-b0a29614c488', 'CARD', 'Cardiology'),
  ('532851a0-70d6-4314-a230-2b6baab8695d', 'ORTH', 'Orthopaedics'),
  ('7d29beef-bda1-4618-bce5-38e52f021cc5', 'ONCO', 'Oncology'),
  ('15a55db8-6b59-4a72-95b7-abd828851f2f', 'SURG', 'General surgery'),
  ('b5ff7c08-b2fa-4b6d-8487-5732eabe8151', 'RAD', 'Radiology')
) as v(id, code, name)
on conflict (id) do nothing;
insert into orbit_erp.shift_templates (id, organization_id, code, name, start_time, end_time, break_minutes)
select v.id::uuid, (select id from orbit.organizations where slug = 'kestrion'), v.code, v.name, v.start_time::time, v.end_time::time, v.break_minutes from (values
  ('7d2ec9a3-08f4-4428-8d4b-bdd1c92fa00c', 'M', 'Morning', '07:00', '15:00', 30),
  ('59d15875-c174-4fc5-9b89-0b359610bd3c', 'A', 'Afternoon', '15:00', '23:00', 30),
  ('c4c8bc08-ac3d-449b-a0c6-fe4603b243e0', 'N', 'Night', '23:00', '07:00', 30),
  ('effc8064-ab01-41ba-8088-477331291c11', 'G', 'General', '09:00', '17:00', 45)
) as v(id, code, name, start_time, end_time, break_minutes)
on conflict (id) do nothing;
insert into orbit_erp.services (id, organization_id, service_code, name, category, department_id, unit)
select v.id::uuid, d.organization_id, v.code, v.name, v.category, d.id, v.unit
from (values
  ('269da50d-88a7-47c1-8cef-39607faf263a', 'CON-GEN', 'General consultation', 'consultation', 'OPD', 'per-visit'),
  ('37ac124a-ec81-4f2d-83e0-598bd0f0595c', 'CON-SPEC', 'Specialist consultation', 'consultation', 'OPD', 'per-visit'),
  ('78896a55-94c7-4caa-aa51-2ff41bc34114', 'EMR-TRIAGE', 'Emergency assessment', 'emergency', 'EMER', 'per-visit'),
  ('8f55ff2b-cca1-4f7e-acbd-79f9a02d6e3b', 'LAB-BLOOD', 'Blood count panel', 'diagnostics-lab', 'LAB', 'per-test'),
  ('04903db2-5dfb-48f3-b537-4c77a3ec6b35', 'LAB-CHEM', 'Chemistry panel', 'diagnostics-lab', 'LAB', 'per-test'),
  ('0120dd15-6e0a-405d-9cdf-36d0c7fa657f', 'IMG-XRAY', 'X-ray imaging', 'diagnostics-imaging', 'RAD', 'per-test'),
  ('f9365595-5281-4620-a9fb-3ca6db6bc13f', 'IMG-US', 'Ultrasound imaging', 'diagnostics-imaging', 'RAD', 'per-test'),
  ('72e015e2-29e2-4b68-af19-66b41decc19a', 'IMG-CT', 'CT imaging', 'diagnostics-imaging', 'RAD', 'per-test'),
  ('15928a7b-a00a-498b-b124-fba772a46581', 'IMG-MRI', 'MRI imaging', 'diagnostics-imaging', 'RAD', 'per-test'),
  ('81a5c8ca-b50e-4d8a-b769-1917c6b51b19', 'CARD-ECG', 'Electrocardiogram', 'diagnostics-lab', 'CARD', 'per-test'),
  ('a4dd17a4-427a-4798-ac2c-2895c136afbf', 'CARD-ANGIO', 'Cardiac catheter procedure', 'procedure', 'CARD', 'per-procedure'),
  ('fdba8a6f-166d-49a2-9ec0-cdb172ece70d', 'ORTH-PROC', 'Orthopaedic procedure', 'procedure', 'ORTH', 'per-procedure'),
  ('d3a7c813-a652-433e-ba28-cc3d492d14aa', 'ONCO-DAY', 'Oncology day-care session', 'day-care', 'ONCO', 'per-session'),
  ('83eb52c0-a1c9-4898-8231-eb1001d62036', 'PROC-MINOR', 'Minor procedure', 'procedure', 'OPD', 'per-procedure'),
  ('764e2b36-f4a4-43d8-b72e-cba1af4f4691', 'WARD-DAY', 'Ward stay', 'inpatient-stay', 'WARD', 'per-day'),
  ('39fe93c6-74f3-4d7d-856d-c932b60f6f46', 'ICU-DAY', 'Critical care stay', 'inpatient-stay', 'ICU', 'per-day'),
  ('aaaa05ac-3a02-46e0-ba21-a2d0ef69257f', 'REHAB-SESS', 'Rehabilitation session', 'therapy', 'REHAB', 'per-session')
) as v(id, code, name, category, department_code, unit)
join orbit_erp.departments d on d.organization_id = (select id from orbit.organizations where slug = 'kestrion') and d.code = v.department_code
on conflict (id) do nothing;
insert into orbit_erp.facility_services (organization_id, facility_id, service_id, is_available)
select f.organization_id, f.id, v.service_id::uuid, true
from (values
  ('avenhurst', '269da50d-88a7-47c1-8cef-39607faf263a'),
  ('avenhurst', '37ac124a-ec81-4f2d-83e0-598bd0f0595c'),
  ('avenhurst', '78896a55-94c7-4caa-aa51-2ff41bc34114'),
  ('avenhurst', '8f55ff2b-cca1-4f7e-acbd-79f9a02d6e3b'),
  ('avenhurst', '04903db2-5dfb-48f3-b537-4c77a3ec6b35'),
  ('avenhurst', '0120dd15-6e0a-405d-9cdf-36d0c7fa657f'),
  ('avenhurst', 'f9365595-5281-4620-a9fb-3ca6db6bc13f'),
  ('avenhurst', '72e015e2-29e2-4b68-af19-66b41decc19a'),
  ('avenhurst', '15928a7b-a00a-498b-b124-fba772a46581'),
  ('avenhurst', '81a5c8ca-b50e-4d8a-b769-1917c6b51b19'),
  ('avenhurst', 'a4dd17a4-427a-4798-ac2c-2895c136afbf'),
  ('avenhurst', 'fdba8a6f-166d-49a2-9ec0-cdb172ece70d'),
  ('avenhurst', '83eb52c0-a1c9-4898-8231-eb1001d62036'),
  ('avenhurst', '764e2b36-f4a4-43d8-b72e-cba1af4f4691'),
  ('avenhurst', '39fe93c6-74f3-4d7d-856d-c932b60f6f46'),
  ('avenhurst', 'aaaa05ac-3a02-46e0-ba21-a2d0ef69257f'),
  ('brackmoor', '269da50d-88a7-47c1-8cef-39607faf263a'),
  ('brackmoor', '37ac124a-ec81-4f2d-83e0-598bd0f0595c'),
  ('brackmoor', '78896a55-94c7-4caa-aa51-2ff41bc34114'),
  ('brackmoor', '8f55ff2b-cca1-4f7e-acbd-79f9a02d6e3b'),
  ('brackmoor', '04903db2-5dfb-48f3-b537-4c77a3ec6b35'),
  ('brackmoor', '0120dd15-6e0a-405d-9cdf-36d0c7fa657f'),
  ('brackmoor', 'f9365595-5281-4620-a9fb-3ca6db6bc13f'),
  ('brackmoor', '81a5c8ca-b50e-4d8a-b769-1917c6b51b19'),
  ('brackmoor', '83eb52c0-a1c9-4898-8231-eb1001d62036'),
  ('brackmoor', '764e2b36-f4a4-43d8-b72e-cba1af4f4691'),
  ('brackmoor', 'aaaa05ac-3a02-46e0-ba21-a2d0ef69257f'),
  ('calderwyn', '269da50d-88a7-47c1-8cef-39607faf263a'),
  ('calderwyn', '37ac124a-ec81-4f2d-83e0-598bd0f0595c'),
  ('calderwyn', '78896a55-94c7-4caa-aa51-2ff41bc34114'),
  ('calderwyn', '8f55ff2b-cca1-4f7e-acbd-79f9a02d6e3b'),
  ('calderwyn', '04903db2-5dfb-48f3-b537-4c77a3ec6b35'),
  ('calderwyn', '0120dd15-6e0a-405d-9cdf-36d0c7fa657f'),
  ('calderwyn', 'f9365595-5281-4620-a9fb-3ca6db6bc13f'),
  ('calderwyn', '81a5c8ca-b50e-4d8a-b769-1917c6b51b19'),
  ('calderwyn', 'fdba8a6f-166d-49a2-9ec0-cdb172ece70d'),
  ('calderwyn', '83eb52c0-a1c9-4898-8231-eb1001d62036'),
  ('calderwyn', '764e2b36-f4a4-43d8-b72e-cba1af4f4691'),
  ('calderwyn', 'aaaa05ac-3a02-46e0-ba21-a2d0ef69257f'),
  ('dunmarrow', '269da50d-88a7-47c1-8cef-39607faf263a'),
  ('dunmarrow', '37ac124a-ec81-4f2d-83e0-598bd0f0595c'),
  ('dunmarrow', '78896a55-94c7-4caa-aa51-2ff41bc34114'),
  ('dunmarrow', '8f55ff2b-cca1-4f7e-acbd-79f9a02d6e3b'),
  ('dunmarrow', '04903db2-5dfb-48f3-b537-4c77a3ec6b35'),
  ('dunmarrow', '0120dd15-6e0a-405d-9cdf-36d0c7fa657f'),
  ('dunmarrow', 'f9365595-5281-4620-a9fb-3ca6db6bc13f'),
  ('dunmarrow', '72e015e2-29e2-4b68-af19-66b41decc19a'),
  ('dunmarrow', '15928a7b-a00a-498b-b124-fba772a46581'),
  ('dunmarrow', '81a5c8ca-b50e-4d8a-b769-1917c6b51b19'),
  ('dunmarrow', 'd3a7c813-a652-433e-ba28-cc3d492d14aa'),
  ('dunmarrow', '83eb52c0-a1c9-4898-8231-eb1001d62036'),
  ('dunmarrow', '764e2b36-f4a4-43d8-b72e-cba1af4f4691'),
  ('dunmarrow', '39fe93c6-74f3-4d7d-856d-c932b60f6f46'),
  ('dunmarrow', 'aaaa05ac-3a02-46e0-ba21-a2d0ef69257f'),
  ('elverton', '269da50d-88a7-47c1-8cef-39607faf263a'),
  ('elverton', '37ac124a-ec81-4f2d-83e0-598bd0f0595c'),
  ('elverton', '78896a55-94c7-4caa-aa51-2ff41bc34114'),
  ('elverton', '8f55ff2b-cca1-4f7e-acbd-79f9a02d6e3b'),
  ('elverton', '04903db2-5dfb-48f3-b537-4c77a3ec6b35'),
  ('elverton', '0120dd15-6e0a-405d-9cdf-36d0c7fa657f'),
  ('elverton', 'f9365595-5281-4620-a9fb-3ca6db6bc13f'),
  ('elverton', '72e015e2-29e2-4b68-af19-66b41decc19a'),
  ('elverton', '15928a7b-a00a-498b-b124-fba772a46581'),
  ('elverton', '81a5c8ca-b50e-4d8a-b769-1917c6b51b19'),
  ('elverton', 'd3a7c813-a652-433e-ba28-cc3d492d14aa'),
  ('elverton', '83eb52c0-a1c9-4898-8231-eb1001d62036'),
  ('elverton', '764e2b36-f4a4-43d8-b72e-cba1af4f4691'),
  ('elverton', '39fe93c6-74f3-4d7d-856d-c932b60f6f46'),
  ('elverton', 'aaaa05ac-3a02-46e0-ba21-a2d0ef69257f'),
  ('farrowgate', '269da50d-88a7-47c1-8cef-39607faf263a'),
  ('farrowgate', '37ac124a-ec81-4f2d-83e0-598bd0f0595c'),
  ('farrowgate', '78896a55-94c7-4caa-aa51-2ff41bc34114'),
  ('farrowgate', '8f55ff2b-cca1-4f7e-acbd-79f9a02d6e3b'),
  ('farrowgate', '04903db2-5dfb-48f3-b537-4c77a3ec6b35'),
  ('farrowgate', '0120dd15-6e0a-405d-9cdf-36d0c7fa657f'),
  ('farrowgate', 'f9365595-5281-4620-a9fb-3ca6db6bc13f'),
  ('farrowgate', '81a5c8ca-b50e-4d8a-b769-1917c6b51b19'),
  ('farrowgate', '83eb52c0-a1c9-4898-8231-eb1001d62036'),
  ('farrowgate', '764e2b36-f4a4-43d8-b72e-cba1af4f4691'),
  ('farrowgate', 'aaaa05ac-3a02-46e0-ba21-a2d0ef69257f')
) as v(facility_slug, service_id)
join orbit.facilities f on f.organization_id = (select id from orbit.organizations where slug = 'kestrion') and f.slug = v.facility_slug
on conflict (facility_id, service_id) do nothing;

commit;
