import type { ErpStore } from './ports.ts';

/** Fail-closed ERP store: every call answers `unavailable` until `ORBIT_LIVE_SOURCES` includes `erp`. */
export function pendingErpStore(fail: () => never): ErpStore {
  return {
    currency: async () => fail(),
    getCoverage: async () => fail(),
    setCoverage: async () => fail(),
    issueBill: async () => fail(),
    listBills: async () => fail(),
    getBill: async () => fail(),
    recordPayment: async () => fail(),
    cancelBill: async () => fail(),
    revenue: async () => fail(),
    reference: async () => fail(),
    facility: async () => fail(),
    today: async () => fail(),
    summary: async () => fail(),
    listStaff: async () => fail(),
    getStaff: async () => fail(),
    createStaff: async () => fail(),
    updateStaff: async () => fail(),
    listDoctors: async () => fail(),
    getDoctor: async () => fail(),
    createDoctor: async () => fail(),
    updateDoctor: async () => fail(),
    addScheduleSlot: async () => fail(),
    updateScheduleSlot: async () => fail(),
    attendanceBoard: async () => fail(),
    recordPunch: async () => fail(),
    staffMonth: async () => fail(),
    listCorrections: async () => fail(),
    getCorrection: async () => fail(),
    requestCorrection: async () => fail(),
    decideCorrection: async () => fail(),
    rosterDay: async () => fail(),
    setRoster: async () => fail(),
    catalogue: async () => fail(),
    createService: async () => fail(),
    updateService: async () => fail(),
    setAvailability: async () => fail(),
    searchPatients: async () => fail(),
    registerPatient: async () => fail(),
    getPatient: async () => fail(),
    updatePatient: async () => fail(),
    listEncounters: async () => fail(),
    openEncounter: async () => fail(),
    getEncounter: async () => fail(),
    updateEncounter: async () => fail(),
    recordDelivery: async () => fail(),
    updateDelivery: async () => fail(),
    audit: async () => fail(),
  };
}
