/**
 * Writes the hospital-operations (ERP) seed for the demo organization:
 *
 *   supabase/seed/0008_erp_reference.sql  settings, departments, specialties,
 *                                          shift patterns, service catalogue,
 *                                          where each service is offered
 *   supabase/seed/0009_erp_people.sql     staff, doctors, consultation slots,
 *                                          rosters, in/out punches
 *   supabase/seed/0010_erp_care.sql       patients, visits, services delivered
 *   data/snapshots/erp-manifest.json      counts, scenarios, configuration, checksum
 *
 * Run: npm run generate:erp --workspace=@orbit/data-gen
 *
 * Deterministic (same output every run) and idempotent (`on conflict do
 * nothing`; visits are inserted in their final state, then their services,
 * which the triggers check against each visit's window). Facility and organization
 * ids are resolved from slugs inside the SQL, never hard-coded. Applying the
 * seed re-checks every row against the database's own integrity triggers.
 *
 * No operator accounts or memberships are written here: those are provisioned
 * out of band (scripts/provision-erp-accounts.ts, ADR 0013 §2).
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ERP_DEMO_CONFIG, ERP_SCENARIOS, generateErpDataset } from "../src/erp.ts";
import { COMPANY_MANIFEST } from "../src/manifest.ts";

const here = dirname(fileURLToPath(import.meta.url));
const seedDir = resolve(here, "../../../supabase/seed");
const snapshotDir = resolve(here, "../../../data/snapshots");

const data = generateErpDataset();
const ORG = `(select id from orbit.organizations where slug = ${q(data.organizationSlug)})`;

function q(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function v(value: string | number | boolean | null): string {
  if (value === null) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  return q(value);
}

/** Splits rows into batches so no single statement is enormous. */
function batches<T>(rows: readonly T[], size = 1000): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < rows.length; i += size) out.push(rows.slice(i, i + size));
  return out;
}

function valuesInsert<T>(
  rows: readonly T[],
  columns: string,
  toValues: (row: T) => readonly (string | number | boolean | null)[],
  statement: (values: string) => string,
): string[] {
  return batches(rows).map((batch) =>
    statement(`(values\n${batch.map((row) => `  (${toValues(row).map(v).join(", ")})`).join(",\n")}\n) as v(${columns})`),
  );
}

function header(title: string): string[] {
  return [
    `-- GENERATED by packages/data-gen/scripts/generate-erp-seed.ts. Do not edit by hand.`,
    `-- ${title}`,
    `-- Fictional demonstration records (ADR 0016). Illustrative; not clinical or employment data.`,
    `-- Idempotent. Requires migration 20261001000100_orbit_erp_operations.sql and seed 0001.`,
    "",
    "begin;",
    "",
  ];
}

// ---------------------------------------------------------------------------
// 0008 reference
// ---------------------------------------------------------------------------
const s = ERP_DEMO_CONFIG.settings;
const reference = [
  ...header("Reference data: settings, departments, specialties, shift patterns, services."),
  `insert into orbit_erp.erp_settings (organization_id, late_grace_minutes, early_exit_grace_minutes,
  punch_window_before_minutes, punch_window_after_minutes, credential_warning_days)
select ${ORG}, ${s.lateGraceMinutes}, ${s.earlyExitGraceMinutes}, ${s.punchWindowBeforeMinutes}, ${s.punchWindowAfterMinutes}, ${s.credentialWarningDays}
on conflict (organization_id) do nothing;`,
  ...valuesInsert(data.departments, "id, code, name", (d) => [d.id, d.code, d.name], (values) =>
    `insert into orbit_erp.departments (id, organization_id, code, name)
select v.id::uuid, ${ORG}, v.code, v.name from ${values}
on conflict (id) do nothing;`),
  ...valuesInsert(data.specialties, "id, code, name", (d) => [d.id, d.code, d.name], (values) =>
    `insert into orbit_erp.specialties (id, organization_id, code, name)
select v.id::uuid, ${ORG}, v.code, v.name from ${values}
on conflict (id) do nothing;`),
  ...valuesInsert(data.shifts, "id, code, name, start_time, end_time, break_minutes", (t) => [t.id, t.code, t.name, t.start, t.end, t.breakMinutes], (values) =>
    `insert into orbit_erp.shift_templates (id, organization_id, code, name, start_time, end_time, break_minutes)
select v.id::uuid, ${ORG}, v.code, v.name, v.start_time::time, v.end_time::time, v.break_minutes from ${values}
on conflict (id) do nothing;`),
  ...valuesInsert(data.services, "id, code, name, category, department_code, unit", (x) => [x.id, x.code, x.name, x.category, x.departmentCode, x.unit], (values) =>
    `insert into orbit_erp.services (id, organization_id, service_code, name, category, department_id, unit)
select v.id::uuid, d.organization_id, v.code, v.name, v.category, d.id, v.unit
from ${values}
join orbit_erp.departments d on d.organization_id = ${ORG} and d.code = v.department_code
on conflict (id) do nothing;`),
  ...valuesInsert(data.availability, "facility_slug, service_id", (a) => [a.facility, a.serviceId], (values) =>
    `insert into orbit_erp.facility_services (organization_id, facility_id, service_id, is_available)
select f.organization_id, f.id, v.service_id::uuid, true
from ${values}
join orbit.facilities f on f.organization_id = ${ORG} and f.slug = v.facility_slug
on conflict (facility_id, service_id) do nothing;`),
  "",
  "commit;",
  "",
];

// ---------------------------------------------------------------------------
// 0009 people
// ---------------------------------------------------------------------------
const people = [
  ...header("Staff, doctors, consultation slots, rosters and in/out punches."),
  ...valuesInsert(
    data.staff,
    "id, facility_slug, department_id, employee_code, display_name, staff_type, designation, employment_status, joined_on, is_critical_role",
    (x) => [x.id, x.facility, x.departmentId, x.employeeCode, x.displayName, x.staffType, x.designation, x.employmentStatus, x.joinedOn, x.isCriticalRole],
    (values) => `insert into orbit_erp.staff (id, organization_id, facility_id, department_id, employee_code, display_name,
  staff_type, designation, employment_status, joined_on, is_critical_role)
select v.id::uuid, f.organization_id, f.id, v.department_id::uuid, v.employee_code, v.display_name,
  v.staff_type, v.designation, v.employment_status, v.joined_on::date, v.is_critical_role
from ${values}
join orbit.facilities f on f.organization_id = ${ORG} and f.slug = v.facility_slug
on conflict (id) do nothing;`,
  ),
  ...valuesInsert(
    data.doctors,
    "staff_id, specialty_id, registration_number, credential_expires_on, employment_type",
    (d) => [d.staffId, d.specialtyId, d.registrationNumber, d.credentialExpiresOn, d.employmentType],
    (values) => `insert into orbit_erp.doctor_profiles (staff_id, organization_id, specialty_id, registration_number,
  credential_expires_on, employment_type)
select v.staff_id::uuid, ${ORG}, v.specialty_id::uuid, v.registration_number, v.credential_expires_on::date, v.employment_type
from ${values}
on conflict (staff_id) do nothing;`,
  ),
  ...valuesInsert(
    data.schedule,
    "id, staff_id, facility_slug, weekday, start_time, end_time",
    (x) => [x.id, x.staffId, x.facility, x.weekday, x.start, x.end],
    (values) => `insert into orbit_erp.doctor_schedules (id, organization_id, staff_id, facility_id, weekday, start_time, end_time)
select v.id::uuid, f.organization_id, v.staff_id::uuid, f.id, v.weekday, v.start_time::time, v.end_time::time
from ${values}
join orbit.facilities f on f.organization_id = ${ORG} and f.slug = v.facility_slug
on conflict (id) do nothing;`,
  ),
  ...valuesInsert(
    data.rosters,
    "staff_id, shift_id, shift_date",
    (r) => [r.staffId, r.shiftId, r.date],
    (values) => `insert into orbit_erp.roster_assignments (organization_id, staff_id, facility_id, shift_template_id, shift_date)
select s.organization_id, s.id, s.facility_id, v.shift_id::uuid, v.shift_date::date
from ${values}
join orbit_erp.staff s on s.id = v.staff_id::uuid
on conflict (staff_id, shift_date) where status = 'planned' do nothing;`,
  ),
  ...valuesInsert(
    data.punches,
    "staff_id, direction, punched_at, idempotency_key",
    (p) => [p.staffId, p.direction, p.at, p.key],
    (values) => `insert into orbit_erp.attendance_punches (organization_id, staff_id, facility_id, direction, punched_at,
  source, recorded_by_membership_id, idempotency_key)
select s.organization_id, s.id, s.facility_id, v.direction, v.punched_at::timestamptz, 'seeded', null, v.idempotency_key::uuid
from ${values}
join orbit_erp.staff s on s.id = v.staff_id::uuid
on conflict (organization_id, idempotency_key) do nothing;`,
  ),
  "",
  "commit;",
  "",
];

// ---------------------------------------------------------------------------
// 0010 care
// ---------------------------------------------------------------------------
const care = [
  ...header("Patients, visits and services delivered."),
  ...valuesInsert(
    data.patients,
    "id, facility_slug, mrn, display_name, sex, birth_year, created_at",
    (p) => [p.id, p.facility, p.mrn, p.displayName, p.sex, p.birthYear, p.createdAt],
    (values) => `insert into orbit_erp.patients (id, organization_id, home_facility_id, mrn, display_name, sex, birth_year,
  created_by_membership_id, created_at, updated_at)
select v.id::uuid, f.organization_id, f.id, v.mrn, v.display_name, v.sex, v.birth_year, null,
  v.created_at::timestamptz, v.created_at::timestamptz
from ${values}
join orbit.facilities f on f.organization_id = ${ORG} and f.slug = v.facility_slug
on conflict (id) do nothing;`,
  ),
  ...valuesInsert(
    data.encounters,
    "id, patient_id, facility_slug, department_id, doctor_id, encounter_type, started_at, ended_at",
    (e) => [e.id, e.patientId, e.facility, e.departmentId, e.doctorId, e.type, e.startedAt, e.endedAt],
    (values) => `insert into orbit_erp.encounters (id, organization_id, patient_id, facility_id, department_id,
  attending_doctor_id, encounter_type, status, started_at, ended_at, created_by_membership_id, created_at, updated_at)
select v.id::uuid, f.organization_id, v.patient_id::uuid, f.id, v.department_id::uuid,
  v.doctor_id::uuid, v.encounter_type, case when v.ended_at is null then 'open' else 'closed' end,
  v.started_at::timestamptz, v.ended_at::timestamptz, null, v.started_at::timestamptz,
  coalesce(v.ended_at::timestamptz, v.started_at::timestamptz)
from ${values}
join orbit.facilities f on f.organization_id = ${ORG} and f.slug = v.facility_slug
on conflict (id) do nothing;`,
  ),
  ...valuesInsert(
    data.deliveries,
    "encounter_id, service_id, performer_id, quantity, performed_at, idempotency_key",
    (d) => [d.encounterId, d.serviceId, d.performerId, d.quantity, d.performedAt, d.key],
    (values) => `insert into orbit_erp.service_deliveries (organization_id, encounter_id, facility_id, service_id,
  performed_by_staff_id, quantity, performed_at, status, idempotency_key, recorded_by_membership_id, created_at, updated_at)
select e.organization_id, e.id, e.facility_id, v.service_id::uuid, v.performer_id::uuid, v.quantity,
  v.performed_at::timestamptz, 'completed', v.idempotency_key::uuid, null, v.performed_at::timestamptz, v.performed_at::timestamptz
from ${values}
join orbit_erp.encounters e on e.id = v.encounter_id::uuid
on conflict (organization_id, idempotency_key) do nothing;`,
  ),
  "",
  "commit;",
  "",
];

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------
const counts = Object.fromEntries(
  Object.entries(data).filter(([, value]) => Array.isArray(value)).map(([key, value]) => [key, (value as unknown[]).length]),
);
const checksum = createHash("sha256").update(JSON.stringify(data)).digest("hex");
const manifest = {
  generatedBy: "packages/data-gen/scripts/generate-erp-seed.ts",
  provenance: "illustrative",
  seed: COMPANY_MANIFEST.seed,
  organization: data.organizationSlug,
  checksum,
  config: ERP_DEMO_CONFIG,
  scenarios: ERP_SCENARIOS,
  counts,
  files: ["supabase/seed/0008_erp_reference.sql", "supabase/seed/0009_erp_people.sql", "supabase/seed/0010_erp_care.sql"],
};

writeFileSync(resolve(seedDir, "0008_erp_reference.sql"), reference.join("\n"));
writeFileSync(resolve(seedDir, "0009_erp_people.sql"), people.join("\n"));
writeFileSync(resolve(seedDir, "0010_erp_care.sql"), care.join("\n"));
mkdirSync(snapshotDir, { recursive: true });
writeFileSync(resolve(snapshotDir, "erp-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`ERP seed written: ${JSON.stringify(counts)}; checksum ${checksum.slice(0, 12)}…`);
